### PR TITLE
Fix default setup.py due to pip10 incompatible changes

### LINKED ISSUE #2: Fix setup.py
Same issue already solved here:

https://github.com/napalm-automation/napalm/pull/692

### PR DESCRIPTION
**Pull request by mbdraks**
Fix #2

### CODE REVIEW

**Comment by ktbyers** [comment]
@barbosm Can you try making this change also and see if it fixes the unit test failure:

```diff
$ git diff
diff --git a/.travis.yml b/.travis.yml
index f23fbda..5d71d3f 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,8 +3,8 @@ python:
 - 2.7
 install:
 - pip install -r requirements-dev.txt
+- pip install -r requirements.txt
 - pip install .
-- pip install -e git+https://github.com/napalm-automation/napalm-base.git@develop#egg=napalm-base
 - pip install coveralls
 
 deploy:
```

**Comment by mbdraks** [comment]
@ktbyers Hi Kirk, I'm not completely sure about how to run the test manually so I looked at the details of the failed build and just followed the exact same steps.

```(env) root@acc49300927a:/tmp/github/fork/napalm-skeleton# py.test --cov-report= test/
Coverage.py warning: --include is ignored because --source is set (include-ignored)
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.5.2, pytest-4.1.1, py-1.7.0, pluggy-0.8.1 -- /tmp/github/fork/napalm-skeleton/env/bin/python3
cachedir: .pytest_cache
rootdir: /tmp/github/fork/napalm-skeleton, inifile: setup.cfg
plugins: pythonpath-0.7.3, json-0.4.0, cov-2.6.1, pylama-7.6.6
collected 34 items                                                                                                                                                        

test/unit/TestDriver.py SKIPPED
test/unit/TestSkeletonDriver.py SKIPPED
test/unit/conftest.py SKIPPED
test/unit/test_getters.py SKIPPED
test/unit/test_getters.py::TestGetter::test_method_signatures PASSED
test/unit/test_getters.py::TestGetter::test_is_alive[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_facts[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_interfaces[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_lldp_neighbors[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_interfaces_counters[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_environment[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_bgp_neighbors[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_lldp_neighbors_detail[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_bgp_config[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_bgp_neighbors_detail[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_arp_table[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_ipv6_neighbors_table[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_ntp_peers[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_ntp_servers[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_ntp_stats[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_interfaces_ip[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_mac_address_table[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_route_to[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_snmp_information[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_probes_config[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_probes_results[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_ping[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_traceroute[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_users[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_optics[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_config[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_config_filtered[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_network_instances[no_test_case_found] SKIPPED
test/unit/test_getters.py::TestGetter::test_get_firewall_policies[no_test_case_found] SKIPPED

--------------------------------------------------- generated json report: /tmp/github/fork/napalm-skeleton/report.json ---------------------------------------------------

----------- coverage: platform linux, python 3.5.2-final-0 -----------
Name                                                                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------------------------
env/lib/python3.5/site-packages/napalm/_SUPPORTED_DRIVERS.py                      1      0   100%
env/lib/python3.5/site-packages/napalm/__init__.py                               14      5    64%   10-12, 16-17
env/lib/python3.5/site-packages/napalm/base/__init__.py                          37     26    30%   70-110
env/lib/python3.5/site-packages/napalm/base/base.py                             127     37    71%   44, 47-48, 51-59, 69, 75-88, 92-94, 100, 106, 124, 132, 140, 159, 179, 195, 203, 209, 215, 221, 661, 1623, 1628-1631
env/lib/python3.5/site-packages/napalm/base/canonical_map.py                      4      0   100%
env/lib/python3.5/site-packages/napalm/base/clitools/__init__.py                  0      0   100%
env/lib/python3.5/site-packages/napalm/base/clitools/cl_napalm.py               139    139     0%   2-288
env/lib/python3.5/site-packages/napalm/base/clitools/cl_napalm_configure.py      40     40     0%   2-67
env/lib/python3.5/site-packages/napalm/base/clitools/cl_napalm_test.py           26     26     0%   2-48
env/lib/python3.5/site-packages/napalm/base/clitools/cl_napalm_validate.py       27     27     0%   2-48
env/lib/python3.5/site-packages/napalm/base/clitools/helpers.py                  45     45     0%   2-126
env/lib/python3.5/site-packages/napalm/base/constants.py                         22      0   100%
env/lib/python3.5/site-packages/napalm/base/exceptions.py                        38      0   100%
env/lib/python3.5/site-packages/napalm/base/helpers.py                          132    105    20%   41-89, 104-139, 157-168, 181-186, 218-224, 250-253, 258-263, 268-270, 288-300, 315-341
env/lib/python3.5/site-packages/napalm/base/mock.py                             129     97    25%   32-36, 40-43, 47-65, 69-79, 85-86, 90, 94, 105-119, 122-124, 127-128, 131-133, 136, 139, 142-151, 154-159, 162-167, 170-172, 175-180, 183-188, 192, 195-200
env/lib/python3.5/site-packages/napalm/base/netmiko_helpers.py                   21     21     0%   12-49
env/lib/python3.5/site-packages/napalm/base/test/__init__.py                      0      0   100%
env/lib/python3.5/site-packages/napalm/base/test/base.py                        414    414     0%   16-593
env/lib/python3.5/site-packages/napalm/base/test/conftest.py                     29      4    86%   24, 40, 46-47
env/lib/python3.5/site-packages/napalm/base/test/double.py                       44     28    36%   24-32, 37-38, 43-44, 49-50, 55-61, 66-78
env/lib/python3.5/site-packages/napalm/base/test/getters.py                     321    205    36%   29-34, 39-56, 75-78, 81-104, 108-112, 117, 137-138, 141, 148, 156-157, 163-164, 170-175, 181-187, 193-198, 204-220, 226-237, 243-249, 255-262, 269-278, 284-289, 296-299, 305-311, 317-323, 329-334, 340-350, 356-361, 370-376, 383-391, 398-404, 410-416, 423-431, 438-445, 451-457, 463-480, 487-490, 498-502, 509-516, 522-526
env/lib/python3.5/site-packages/napalm/base/test/helpers.py                      15     11    27%   12-31
env/lib/python3.5/site-packages/napalm/base/test/models.py                       39      0   100%
env/lib/python3.5/site-packages/napalm/base/utils/__init__.py                     0      0   100%
env/lib/python3.5/site-packages/napalm/base/utils/jinja_filters.py               21     14    33%   12, 21-25, 30-41, 46-53
env/lib/python3.5/site-packages/napalm/base/utils/py23_compat.py                 18      5    72%   15, 24-28
env/lib/python3.5/site-packages/napalm/base/utils/string_parsers.py              61     61     0%   2-124
env/lib/python3.5/site-packages/napalm/base/validate.py                         131    116    11%   22-30, 34-40, 44-71, 75-111, 115-147, 152-167, 172-175, 179-201
env/lib/python3.5/site-packages/napalm/eos/__init__.py                            3      3     0%   15-18
env/lib/python3.5/site-packages/napalm/eos/eos.py                               835    835     0%   15-1782
env/lib/python3.5/site-packages/napalm/eos/utils/__init__.py                      0      0   100%
env/lib/python3.5/site-packages/napalm/ios/__init__.py                            3      3     0%   15-19
env/lib/python3.5/site-packages/napalm/ios/ios.py                              1203   1203     0%   16-2435
env/lib/python3.5/site-packages/napalm/iosxr/__init__.py                          8      8     0%   16-29
env/lib/python3.5/site-packages/napalm/iosxr/constants.py                         3      3     0%   3-7
env/lib/python3.5/site-packages/napalm/iosxr/iosxr.py                           820    820     0%   16-1821
env/lib/python3.5/site-packages/napalm/junos/__init__.py                          2      2     0%   15-18
env/lib/python3.5/site-packages/napalm/junos/constants.py                         4      4     0%   3-20
env/lib/python3.5/site-packages/napalm/junos/junos.py                          1055   1055     0%   16-2148
env/lib/python3.5/site-packages/napalm/junos/utils/__init__.py                    0      0   100%
env/lib/python3.5/site-packages/napalm/junos/utils/junos_views.py                16     16     0%   4-28
env/lib/python3.5/site-packages/napalm/nxos/__init__.py                           9      9     0%   16-30
env/lib/python3.5/site-packages/napalm/nxos/nxos.py                             678    678     0%   16-1113
env/lib/python3.5/site-packages/napalm/nxos/utils/__init__.py                     0      0   100%
env/lib/python3.5/site-packages/napalm/nxos_ssh/__init__.py                       8      8     0%   16-30
env/lib/python3.5/site-packages/napalm/nxos_ssh/nxos_ssh.py                     896    896     0%   16-1518
env/lib/python3.5/site-packages/napalm/nxos_ssh/utils/__init__.py                 0      0   100%
-----------------------------------------------------------------------------------------------------------
TOTAL                                                                          7438   6969     6%

================================================================== 1 passed, 33 skipped in 6.60 seconds ===================================================================
(env) root@acc49300927a:/tmp/github/fork/napalm-skeleton# 
```
Is this ok ?

BTW, tks for your python course, I've learned a great deal from it and that's why I'm now trying to create a new napalm driver :)

**Comment by ktbyers** [comment]
Yes, the unit tests run fine...the issue is that Travis tries to install a dependency that is now deprecated.

**Comment by ktbyers** [comment]
Closed duplicate with:

https://github.com/napalm-automation/napalm-skeleton/pull/6

**Pull request closed without merging**
